name: End-to-End Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  e2e-tests:
    name: Run Playwright Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Wait for Vercel deployment
        # For push to main, wait for deployment to complete
        # For PRs, a preview deployment should already be available
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "Waiting for Vercel deployment to complete (30 seconds)..."
          sleep 30

      - name: Run Playwright tests
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ github.event_name == 'pull_request' && format('https://{0}', secrets.VERCEL_PREVIEW_URL) || 'https://jfk-rag-vercel.vercel.app' }}
        run: npm run test:e2e

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30 